# -*- coding: utf-8 -*-
"""Copy of Copy of Diplom__code_my_results.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BNDagJvPC9pjLYWx9fR4WVs3pOy05uHI
"""

# Commented out IPython magic to ensure Python compatibility.
import torch
import torchvision
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.nn.functional as F
from torchvision.datasets import CIFAR10
from torchvision.transforms import ToTensor
from torchvision.utils import make_grid
from torch.utils.data.dataloader import DataLoader
from torch.utils.data import random_split
# %matplotlib inline
from torchvision import transforms



transform_train = transforms.Compose(
    [transforms.RandomCrop(32, padding=4, padding_mode='reflect'),
     transforms.RandomHorizontalFlip(),
     transforms.ToTensor(),
     transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010),inplace=True)])
transform_test = transforms.Compose([
    transforms.ToTensor(),
     transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010),inplace=True)
])
batch_size = 4

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_train)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2, pin_memory=True)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_test)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2, pin_memory=True)

def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

#classes = trainset.classes

#dataiter = iter(trainloader)
#images, labels = dataiter.next()

# show images
#imshow(torchvision.utils.make_grid(images))
# print labels
#print(' '.join(f'{classes[labels[j]]:5s}' for j in range(4)))

#dataset_size = len(trainset)

#x = []
#for i in range(dataset_size):
#    x.append(trainset[i][1])
#uimg = torch.tensor(x).unique(sorted=True)
#uimg_count = torch.stack([(torch.tensor(x)==i).sum() for i in uimg])
#for i in range(len(uimg)):
#    print(f'{trainset.classes[i]}: {uimg_count[i].item()} count')

#plt.style.use('ggplot')

#x_pos = [i for i, _ in enumerate(classes)]

#plt.bar(classes, uimg_count, color='blue')
#plt.xlabel("Classes")
#plt.ylabel("Count of images")
#plt.title("Cifar 10 dataset")

#plt.xticks(x_pos, classes,rotation = 45)

#plt.show()

def get_default_device():
    """Pick GPU if available, else CPU"""
    if torch.cuda.is_available():
        return torch.device('cuda')
    else:
        return torch.device('cpu')

def to_device(data, device):
    """Move tensor(s) to chosen device"""
    if isinstance(data, (list,tuple)):
        return [to_device(x, device) for x in data]
    return data.to(device, non_blocking=True)

class DeviceDataLoader():
    """Wrap a dataloader to move data to a device"""
    def __init__(self, dl, device):
        self.dl = dl
        self.device = device

    def __iter__(self):
        """Yield a batch of data after moving it to device"""
        for b in self.dl:
            yield to_device(b, self.device)

    def __len__(self):
        """Number of batches"""
        return len(self.dl)

device = get_default_device()
device

train_dl = DeviceDataLoader(trainloader, device)
test_dl = DeviceDataLoader(testloader, device)

def accuracy(outputs, labels):
    _, preds = torch.max(outputs, dim=1)
    return torch.tensor(torch.sum(preds == labels).item() / len(preds))

class ImageClassificationBase(nn.Module):
    def training_step(self, batch):
        images, labels = batch
        out = self(images)                  # Generate predictions
        loss = F.cross_entropy(out, labels) # Calculate loss
        return loss

    def validation_step(self, batch):
        images, labels = batch
        out = self(images)                    # Generate predictions
        loss = F.cross_entropy(out, labels)   # Calculate loss
        acc = accuracy(out, labels)           # Calculate accuracy
        return {'val_loss': loss.detach(), 'val_acc': acc}

    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        batch_accs = [x['val_acc'] for x in outputs]
        epoch_acc = torch.stack(batch_accs).mean()      # Combine accuracies
        return {'val_loss': epoch_loss.item(), 'val_acc': epoch_acc.item()}

    def epoch_end(self, epoch, result):
        print("Epoch [{}], last_lr: {:.5f}, train_loss: {:.4f}, val_loss: {:.4f}, val_acc: {:.4f}".format(
            epoch + 1, result['lrs'][-1], result['train_loss'], result['val_loss'], result['val_acc']))

def parameter_count(model):
  return sum(p.numel() for p in model.parameters() if p.requires_grad)

def conv_block(in_channels, out_channels, pool=False):
    layers = [nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
              nn.BatchNorm2d(out_channels),
              nn.ReLU(inplace=True)]
    if pool: layers.append(nn.MaxPool2d(2))
    return nn.Sequential(*layers)



class ResNet9(ImageClassificationBase):
    def __init__(self, in_channels, num_classes):
        super().__init__()

        self.conv1 = conv_block(in_channels, 64)
        self.conv2 = conv_block(64, 128, pool=True)
        self.res1 = nn.Sequential(conv_block(128, 128), conv_block(128, 128))

        self.conv3 = conv_block(128, 256, pool=True)
        self.conv4 = conv_block(256, 512, pool=True)
        self.res2 = nn.Sequential(conv_block(512, 512), conv_block(512, 512))

        self.classifier = nn.Sequential(nn.AvgPool2d(4),
                                        nn.Flatten(),
                                        nn.Linear(512, num_classes),
                                        nn.LogSoftmax(dim=1))

    def forward(self, xb):
        out = self.conv1(xb)
        out = self.conv2(out)
        out = self.res1(out) + out
        out = self.conv3(out)
        out = self.conv4(out)
        out = self.res2(out) + out
        out = self.classifier(out)
        return out
    

class my_layer(nn.Module):
    def __init__(self, img_channels) -> None:
        super().__init__()
        filter1 = torch.Tensor([[[0,  1,  0],
                                [0, -2,  0],
                                [0,  1,  0]]])
        filter2 = torch.Tensor([[[0,  0,  0],
                                [1, -2,  1],
                                [0,  0,  0]]])
        filter3 = torch.Tensor([[[0,  0,  0],
                                 [0,  1,  0],
                                 [0,  0,  0]]])
        self.register_buffer("filter1", filter1)
        self.register_buffer("filter2", filter2)
        self.register_buffer("filter3", filter3)
        self.weight1_1 = nn.Parameter(torch.Tensor(3, 3, 1))
        self.weight1_2 = nn.Parameter(torch.Tensor(3, 3, 1))
        self.weight1_3 = nn.Parameter(torch.Tensor(3, 3, 1))
        #self.bias = nn.Parameter(torch.Tensor(1))
        nn.init.xavier_normal_(self.weight1_1)
        nn.init.xavier_normal_(self.weight1_2)
        nn.init.xavier_normal_(self.weight1_3)

        self.bn01 = nn.BatchNorm2d(img_channels)
        self.relu = nn.ReLU(inplace=True)


    def forward(self, x:  torch.Tensor) -> torch.Tensor:
        self.kernel1_1 = torch.einsum("ijk, klm -> ijlm", self.weight1_1, self.filter1)
        self.kernel1_2 = torch.einsum("ijk, klm -> ijlm", self.weight1_2, self.filter2)
        self.kernel1_3 = torch.einsum("ijk, klm -> ijlm", self.weight1_3, self.filter3)
        x = F.conv2d(x, weight=self.kernel1_1+self.kernel1_2+self.kernel1_3, padding=1)
        x = self.bn01(x)
        x = self.relu(x)
        return x

class ResNet9_par(ImageClassificationBase):
    def __init__(self, in_channels, num_classes):
        super().__init__()
        self.mylayer_1 = my_layer(img_channels=in_channels)
        self.conv1 = conv_block(in_channels, 64)
        self.conv2 = conv_block(64, 128, pool=True)
        self.res1 = nn.Sequential(conv_block(128, 128), conv_block(128, 128))

        self.conv3 = conv_block(128, 256, pool=True)
        self.conv4 = conv_block(256, 512, pool=True)
        self.res2 = nn.Sequential(conv_block(512, 512), conv_block(512, 512))

        self.classifier = nn.Sequential(nn.AvgPool2d(4),
                                        nn.Flatten(),
                                        nn.Linear(512, num_classes),
                                        nn.LogSoftmax(dim=1))

    def forward(self, xb):
        x = self.mylayer_1(xb)
        out = self.conv1(x)
        out = self.conv2(out)
        out = self.res1(out) + out
        out = self.conv3(out)
        out = self.conv4(out)
        out = self.res2(out) + out
        out = self.classifier(out)
        return out


class ResNet9_par_2(ImageClassificationBase):
    def __init__(self, in_channels, num_classes):
        super().__init__()
        self.mylayer_1 = my_layer(img_channels=in_channels)
        self.mylayer_2 = my_layer(img_channels=in_channels)
        self.conv1 = conv_block(in_channels, 64)
        self.conv2 = conv_block(64, 128, pool=True)
        self.res1 = nn.Sequential(conv_block(128, 128), conv_block(128, 128))

        self.conv3 = conv_block(128, 256, pool=True)
        self.conv4 = conv_block(256, 512, pool=True)
        self.res2 = nn.Sequential(conv_block(512, 512), conv_block(512, 512))

        self.classifier = nn.Sequential(nn.AvgPool2d(4),
                                        nn.Flatten(),
                                        nn.Linear(512, num_classes),
                                        nn.LogSoftmax(dim=1))

    def forward(self, xb):
        x = self.mylayer_1(xb)
        x = self.mylayer_2(x)
        out = self.conv1(x)
        out = self.conv2(out)
        out = self.res1(out) + out
        out = self.conv3(out)
        out = self.conv4(out)
        out = self.res2(out) + out
        out = self.classifier(out)
        return out



class ResNet9_par_3(ImageClassificationBase):
    def __init__(self, in_channels, num_classes):
        super().__init__()
        self.mylayer_1 = my_layer(img_channels=in_channels)
        self.mylayer_2 = my_layer(img_channels=in_channels)
        self.mylayer_3 = my_layer(img_channels=in_channels)
        self.conv1 = conv_block(in_channels, 64)
        self.conv2 = conv_block(64, 128, pool=True)
        self.res1 = nn.Sequential(conv_block(128, 128), conv_block(128, 128))

        self.conv3 = conv_block(128, 256, pool=True)
        self.conv4 = conv_block(256, 512, pool=True)
        self.res2 = nn.Sequential(conv_block(512, 512), conv_block(512, 512))

        self.classifier = nn.Sequential(nn.AvgPool2d(4),
                                        nn.Flatten(),
                                        nn.Linear(512, num_classes),
                                        nn.LogSoftmax(dim=1))

    def forward(self, xb):
        x = self.mylayer_1(xb)
        x = self.mylayer_2(x)
        x = self.mylayer_3(x)
        out = self.conv1(x)
        out = self.conv2(out)
        out = self.res1(out) + out
        out = self.conv3(out)
        out = self.conv4(out)
        out = self.res2(out) + out
        out = self.classifier(out)
        return out


class ResNet9_par_4(ImageClassificationBase):
    def __init__(self, in_channels, num_classes):
        super().__init__()
        self.mylayer_1 = my_layer(img_channels=in_channels)
        self.mylayer_2 = my_layer(img_channels=in_channels)
        self.mylayer_3 = my_layer(img_channels=in_channels)
        self.mylayer_4 = my_layer(img_channels=in_channels)
        self.conv1 = conv_block(in_channels, 64)
        self.conv2 = conv_block(64, 128, pool=True)
        self.res1 = nn.Sequential(conv_block(128, 128), conv_block(128, 128))

        self.conv3 = conv_block(128, 256, pool=True)
        self.conv4 = conv_block(256, 512, pool=True)
        self.res2 = nn.Sequential(conv_block(512, 512), conv_block(512, 512))

        self.classifier = nn.Sequential(nn.AvgPool2d(4),
                                        nn.Flatten(),
                                        nn.Linear(512, num_classes),
                                        nn.LogSoftmax(dim=1))

    def forward(self, xb):
        x = self.mylayer_1(xb)
        x = self.mylayer_2(x)
        x = self.mylayer_3(x)
        x = self.mylayer_4(x)
        out = self.conv1(x)
        out = self.conv2(out)
        out = self.res1(out) + out
        out = self.conv3(out)
        out = self.conv4(out)
        out = self.res2(out) + out
        out = self.classifier(out)
        return out


class ResNet9_par_5(ImageClassificationBase):
    def __init__(self, in_channels, num_classes):
        super().__init__()
        self.mylayer_1 = my_layer(img_channels=in_channels)
        self.mylayer_2 = my_layer(img_channels=in_channels)
        self.mylayer_3 = my_layer(img_channels=in_channels)
        self.mylayer_4 = my_layer(img_channels=in_channels)
        self.mylayer_5 = my_layer(img_channels=in_channels)
        self.conv1 = conv_block(in_channels, 64)
        self.conv2 = conv_block(64, 128, pool=True)
        self.res1 = nn.Sequential(conv_block(128, 128), conv_block(128, 128))

        self.conv3 = conv_block(128, 256, pool=True)
        self.conv4 = conv_block(256, 512, pool=True)
        self.res2 = nn.Sequential(conv_block(512, 512), conv_block(512, 512))

        self.classifier = nn.Sequential(nn.AvgPool2d(4),
                                        nn.Flatten(),
                                        nn.Linear(512, num_classes),
                                        nn.LogSoftmax(dim=1))


    def forward(self, xb):
        x = self.mylayer_1(xb)
        x = self.mylayer_2(x)
        x = self.mylayer_3(x)
        x = self.mylayer_4(x)
        x = self.mylayer_5(x)
        out = self.conv1(x)
        out = self.conv2(out)
        out = self.res1(out) + out
        out = self.conv3(out)
        out = self.conv4(out)
        out = self.res2(out) + out
        out = self.classifier(out)
        return out



@torch.no_grad()
def evaluate(model, val_loader):
    model.eval()
    outputs = [model.validation_step(batch) for batch in val_loader]
    return model.validation_epoch_end(outputs)

def get_lr(optimizer):
    for param_group in optimizer.param_groups:
        return param_group['lr']

def fit_one_cycle(epochs, max_lr, model, train_loader, val_loader,
                  weight_decay=0, grad_clip=None, opt_func=torch.optim.SGD):
    torch.cuda.empty_cache()
    history = []

    optimizer = opt_func(model.parameters(), max_lr, weight_decay=weight_decay)
    sched = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr, epochs=epochs, steps_per_epoch=len(train_loader))
    best_accuracy = 0.93
    for epoch in range(epochs):
        torch.cuda.empty_cache()
        # Training Phase
        model.train()
        train_losses = []
        lrs = []
        for batch in train_loader:
            loss = model.training_step(batch)
            train_losses.append(loss)
            loss.backward()

            # Gradient clipping
            if grad_clip:
                nn.utils.clip_grad_value_(model.parameters(), grad_clip)

            optimizer.step()
            optimizer.zero_grad()

            # Record & update learning rate
            lrs.append(get_lr(optimizer))
            sched.step()

        # Validation phase
        model.eval()
        result = evaluate(model, val_loader)
        result['train_loss'] = torch.stack(train_losses).mean().item()
        result['lrs'] = lrs
        model.epoch_end(epoch, result)
        history.append(result)
        if  history_original[-1]['val_acc'] > best_accuracy:
            best_accuracy = history_original[-1]['val_acc']
            #torch.save(model, f'/content/drive/MyDrive/diplom_experiments/best_{model}_original.pth')
            #torch.save(model.state_dict(), f'/content/drive/MyDrive/diplom_experiments/{model}_original_parameters.pth')
    return history



model_original = to_device(ResNet9(3, 10),  device)
model_parabolic_1 = to_device(ResNet9_par(3, 10), device)
model_parabolic_2 = to_device(ResNet9_par_2(3, 10), device)
model_parabolic_3 = to_device(ResNet9_par_3(3, 10), device)
model_parabolic_4 = to_device(ResNet9_par_4(3, 10), device)
model_parabolic_5 = to_device(ResNet9_par_5(3, 10), device)

models = (model_original, model_parabolic_1, model_parabolic_2, model_parabolic_3, model_parabolic_4, model_parabolic_5)
history_original = [evaluate(model_original, test_dl)]
history_parabolic_1 = [evaluate(model_parabolic_1, test_dl)]
history_parabolic_2 = [evaluate(model_parabolic_2, test_dl)]
history_parabolic_3 = [evaluate(model_parabolic_3, test_dl)]
history_parabolic_4 = [evaluate(model_parabolic_4, test_dl)]
history_parabolic_5 = [evaluate(model_parabolic_5, test_dl)]

histories  = [history_original, history_parabolic_1, history_parabolic_2, history_parabolic_3, history_parabolic_4, history_parabolic_5]

import pickle
print(histories)

epochs = 100
max_lr = 0.01
grad_clip = 0.1
weight_decay = 1e-4
opt_func = torch.optim.Adam


for model in models:
    print(parameter_count(model))


for ind, model in enumerate(models):
    histories[ind] += fit_one_cycle(epochs, max_lr, model_original, train_dl, test_dl,
                             grad_clip=grad_clip,
                             weight_decay=weight_decay,
                             opt_func=opt_func)

    torch.save(model.state_dict(), f'/home/rafayel.veziryan/cnn_exp/results/cifar10_resnet9/{model._get_name()}_bst.pt')
    with open(f'/home/rafayel.veziryan/cnn_exp/results/cifar10_resnet9/{model._get_name()}_list.pkl', 'wb') as fp:
        pickle.dump(histories, fp)
        print('History saved successfully to file')
